# Generated by Django 2.2.1 on 2019-05-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessageView',
            fields=[
                ('msg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_from', models.CharField(max_length=100)),
                ('email_to', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('read', models.BooleanField()),
            ],
            options={
                'db_table': 'user_message_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateMessages',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_time', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('read', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
