# Generated by Django 2.2.1 on 2019-05-21 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_messages', '0002_auto_20190521_1405'),
    ]

    operations = [
        migrations.RunSQL("""
           drop view if exists user_messages_view;

           create view user_messages_view as (
                   with emails_to as (
                       select email as email_to, title
                       from messages pm
                                join users u on pm.user_to = u.user_id
                   ),
                        emails_from as (
                            select email as email_from, title
                            from messages pm
                                     join users u3 on pm.user_from = u3.user_id
                        )

                   select email_from, email_to, pm.title, pm.msg_id, pm.read
                   from messages pm,
                        emails_from,
                        emails_to
               );""")
    ]
