# Generated by Django 2.2.1 on 2019-05-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bands', '0001_initial'),
        ('adverts', '0001_initial'),
        ('muzi_muzi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='band',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bands.Band'),
        ),
        migrations.AddField(
            model_name='advert',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='muzi_muzi.Genre'),
        ),
        migrations.AddField(
            model_name='advert',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='muzi_muzi.Profession'),
        ),
    ]
