# Generated by Django 2.2.1 on 2019-05-22 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0004_auto_20190521_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='adverts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
