# Generated by Django 2.2.1 on 2019-05-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('muzi_muzi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandMemberView',
            fields=[
                ('band_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('members', models.TextField()),
            ],
            options={
                'db_table': 'band_members_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('band_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('year_founded', models.DateField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('homepage', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='muzi_muzi.City')),
                ('genres', models.ManyToManyField(db_table='band_genre', to='muzi_muzi.Genre')),
            ],
            options={
                'db_table': 'band',
            },
        ),
    ]
