# Generated by Django 2.2.1 on 2019-05-22 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_auto_20190521_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='members',
            field=models.ManyToManyField(db_table='user_band', related_name='bands', to=settings.AUTH_USER_MODEL),
        ),
    ]
