# Generated by Django 2.2.1 on 2019-05-21 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""

            drop view if exists user_list_view;
            drop view if exists user_profile_view;
             create view user_list_view as (
                    select u.user_id,
                           u.first_name,
                           u.email,
                           u.photo_url,
                           c.name                               city,
                           string_agg(distinct p.name, ', ') as prof,
                           string_agg(distinct g.name, ', ') as genre
                    from users u
                             join city c on u.city_id = c.city_id
                             join users_professions up on u.user_id = up.users_id
                             join profession p on up.profession_id = p.prof_id
                             join users_genres ug on u.user_id = ug.users_id
                             join genre g on ug.genre_id = g.genre_id
                    group by u.first_name, u.email, u.photo_url, c.name, u.user_id
                );

                create view user_profile_view as (
                    select u.user_id,
                           u.first_name,
                           u.last_name,
                           u.username,
                           u.email,
                           u.description,
                           u.photo_url                          photo,
                           c.name                               city,
                           (select v.url from videos v where u.video_id = v.video_id)
                           video,
                           string_agg(distinct p.name, ', ') as prof,
                           string_agg(distinct g.name, ', ') as genre,
                           (select string_agg(b.name, ', ')
                                     from band b
                                              join user_band ub on b.band_id = ub.band_id
                                     where ub.users_id = u.user_id)                      as bands
                    from users u
                             join city c on u.city_id = c.city_id
                             join users_professions up on u.user_id = up.users_id
                             join profession p on up.profession_id = p.prof_id
                             join users_genres ug on u.user_id = ug.users_id
                             join genre g on ug.genre_id = g.genre_id
                      group by u.user_id, u.first_name, u.email, u.photo_url, c.name, video
                );""")
    ]
