# Generated by Django 2.2.1 on 2019-07-02 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_changed_not_null_values_in_key_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
