# Generated by Django 2.2.1 on 2019-07-02 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190702_1114'),
        ('users', '0006_verificationtoken_model_and_is_active_default_false'),
    ]

    operations = [
    ]
