# Generated by Django 2.2.1 on 2019-05-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzi_muzi', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
                                insert into role (name) values ('USER');
                                insert into role (name) values ('ADMIN');

                                insert into profession (name) values ('Electric Guitar');
                                insert into profession (name) values ('Electric Bass');
                                insert into profession (name) values ('Piano');
                                insert into profession (name) values ('Drums');
                                insert into profession (name) values ('Keyboards');
                                insert into profession (name) values ('Flute');
                                insert into profession (name) values ('Classical Guitar');
                                insert into profession (name) values ('Violin');
                                insert into profession (name) values ('Saxophone');
                                insert into profession (name) values ('Vocal');

                                insert into genre (name) values ('Hard Rock');
                                insert into genre (name) values ('EDM');
                                insert into genre (name) values ('Jazz');
                                insert into genre (name) values ('Dub step');
                                insert into genre (name) values ('Pop');
                                insert into genre (name) values ('Folk');
                                insert into genre (name) values ('Indie Rock');
                                insert into genre (name) values ('Punk');
                                insert into genre (name) values ('Metal');
                                insert into genre (name) values ('Blues');
                                insert into genre (name) values ('Country');
                                insert into genre (name) values ('Hip-hop');
                                insert into genre (name) values ('RnB');
                                """)
    ]
