# Generated by Django 2.2.1 on 2019-05-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzi_muzi', '0002_advertlistview_userlistview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertView',
            fields=[
                ('advert_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('band_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'advert_view',
                'managed': False,
            },
        ),
    ]
