# Generated by Django 2.2.1 on 2019-05-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzi_muzi', '0003_advertview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandMemberView',
            fields=[
                ('band_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('members', models.TextField()),
            ],
            options={
                'db_table': 'band_members_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMessageView',
            fields=[
                ('msg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_from', models.CharField(max_length=100)),
                ('email_to', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('read', models.BooleanField()),
            ],
            options={
                'db_table': 'user_message_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfileView',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=255)),
                ('prof', models.TextField()),
                ('genre', models.TextField()),
                ('bands', models.TextField()),
            ],
            options={
                'db_table': 'user_profile_view',
                'managed': False,
            },
        ),
    ]
